### ISSUE TITLE
Get Error when create new project , do pod install and build

### ISSUE THREAD

**Issue by aginika** [furushchev/ROSiOS#1]
I created simple view project and did `pod install` with Podfile.
Launguage is Objective-C and Devices is Universal

```
pod "ROSiOS"
pod "ROSiOS-std_msgs"
```

Then, after that, I build it. It failed.
![2015-01-24 23 03 52](https://cloud.githubusercontent.com/assets/3803922/5887596/5a7f8be8-a41d-11e4-8c8d-49764879ed1d.png)

**Comment by furushchev** [comment]
This is because of linking ros/boost related frameworks (C++ codes) as Objective-C (which should be linked as Objective-C++ objects).
Brief fix is to rename `main.m` file to `main.mm` in your project. (`.mm` is an extension of Objective-C++)
(by renaming, Xcode switches compiler/linker from Obj-C to Obj-C++ on your main file.)

**Comment by aginika** [comment]
Oh, Thanks! That's it!
